### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL

### ISSUE THREAD

**Issue by wujekbogdan** [ngryman/cz-emoji#49]
I updated `cz-emoji` to `1.3.0` and now I'm getting the following error when running `git cz`:

```
(node:2705) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at readFile (fs.js:295:10)
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at readFile (internal/util.js:277:12)
    at loadConfig (/Users/wujekbogdan/htdocs/cm-web-app/node_modules/cz-emoji/index.js:16:10)
    at async getConfig (/Users/wujekbogdan/htdocs/cm-web-app/node_modules/cz-emoji/index.js:36:6)
(node:2705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ngryman** [comment]
This should be fixed in `1.3.1`. Thanks for raising this!
