### ISSUE TITLE
Expected `columns` to be a number, got undefined.

### ISSUE THREAD

**Issue by norwegianbegginer** [ngryman/cz-emoji#57]
**Describe the bug**
I\ve got undefined for columns when commiting.

**To Reproduce**

1. Run the script
2. Select emoji
3. Fill out the subject etc
4. See error when formating

**Expected behavior**
Show formatted commit in editor.

**Additional context**
```(node:9740) UnhandledPromiseRejectionWarning: TypeError: Expected `columns` to be a number, got undefined
    at module.exports (C:\Users\rcich\assembless.tech\node_modules\cz-emoji\node_modules\cli-truncate\index.js:18:9)
    at format (C:\Users\rcich\assembless.tech\node_modules\cz-emoji\index.js:163:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of aness on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ngryman** [comment]
I just published a new version. Could you check that it's still happening? You can install it with: `npm install cz-emoji@canary`. Thanks!
